### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ahmetozalp** [molenzwiebel/Impostor#6]
```
[+] Starting impostor...
[+] Connected to database!
[+] Connected to Discord as AmongUS - BOT
[+] Command: !amongus eu SPFMQQ
[+] Creating new AU session for SPFMQQ on Europe
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/ahmetozalp/Desktop/Impostor/client/bin/Debug/netcoreapp3.1/client ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /Users/ahmetozalp/Desktop/Impostor/client/bin/Debug/netcoreapp3.1/client',
  path: '/Users/ahmetozalp/Desktop/Impostor/client/bin/Debug/netcoreapp3.1/client',
  spawnargs: [ '172.105.251.170', 'SPFMQQ' ]
```

**Comment by DarrenAlex** [comment]
Try doing `chmod -R 777 <directory name of the whole bot`

**Comment by DarrenAlex** [comment]
Example: `chmod -R 777 discord-bot`

**Comment by ahmetozalp** [comment]
problem not fixed

**Comment by DarrenAlex** [comment]
Try `chmod -R a+x <dir name of bot>`. Worked for me.
